### ISSUE TITLE
how to make "collapsed" TRACE logs default ?

### ISSUE THREAD

**Issue by jhegedus42** [jokade/slogging#37]
Hi,

Here is how it is possible to collapse TRACE logs, perhaps using something like this  : https://mariusschulz.com/blog/advanced-javascript-logging-using-console-group

Something like this : 
![image](https://user-images.githubusercontent.com/6671476/53863446-eb126e80-3ff2-11e9-98c1-cf49e1772394.png)

Is it possible to do the same with slogger ?

For me a trace looks like this : 
![image](https://user-images.githubusercontent.com/6671476/53863275-73444400-3ff2-11e9-8b5f-3288801545da.png)
But it would be much nicer to have these "TRACE"-s already folded by default , like this : 
![image](https://user-images.githubusercontent.com/6671476/53863332-9cfd6b00-3ff2-11e9-99cf-934129a211db.png)

**Comment by jhegedus42** [comment]
answer:

Put the following into the JS console before executing the code : 

```
console.oldTrace=console.trace
f =  function(x) { console.groupCollapsed(x);console.oldTrace(x); console.groupEnd()}
console.trace=f
```

Then you get:

![image](https://user-images.githubusercontent.com/6671476/53968388-9e688980-40ff-11e9-8ac4-ff3a356713f6.png)

**Comment by vanowm** [comment]
@jhegedus42 Since trace can accept multiple arguments, it's better use `apply` instead, also it looks better if it doesn't show same arguments twice (typescript friendly version)
```
{
  const oldTrace= console.trace;
  console.trace = (...args) => { console.groupCollapsed.apply(console, args); oldTrace(""); console.groupEnd()};
}
```
