### ISSUE TITLE
PrintLogger.printTimestamp is missing from 0.6.1

### ISSUE THREAD

**Issue by DuckOfDoom** [jokade/slogging#40]
Hello. Im having trouble using PrintLogger in a clean project as it does not have a field `printTimestamp` for some reason.

My build.sbt:
```
name := "loggingtest"
version := "0.1"
scalaVersion := "2.12.4"
libraryDependencies += "biz.enef" %% "slogging" % "0.6.1"
```

Main.scala:
```
import slogging._

object Main {

  def main(args: Array[String]): Unit = {

    LoggerConfig.factory = PrintLoggerFactory()
    LoggerConfig.level = LogLevel.TRACE

    PrintLogger.printTimestamp = true

  }
}
```

![image](https://user-images.githubusercontent.com/1259961/62377026-a6134980-b54a-11e9-8ba4-b7190c9da306.png)

Can you please point me to the right direction? Maybe there is some conflict of versions in maven repository or something?

Sorry for a basic question, I dont really have a lot of experience with Scala environment and I can't figure out what might be the problem.

**Comment by jokade** [comment]
@DuckOfDoom sorry, my bad. The Readme is not up-to-date on this topic.
`PrintLogger` has no member `printTimestamp`; instead to configure this feature you need to configure the used `MessageFormatter`. Could you please try the following:
```scala
PrintLoggerFactory.formatter = new MessageFormatter.DefaultPrefixFormatter(true,true,true)
```

**Comment by DuckOfDoom** [comment]
@jokade Thanks, got everything working. I went over MessageFormatters in source code, but was not sure that it's the most efficient way of doing things.

**Comment by jokade** [comment]
@DuckOfDoom well I really need to do some housekeeping on this lib and provide a simpler way to do this... thanks for the report
