### ISSUE TITLE
New release targetting Scala Native 0.4.0-M2

### ISSUE THREAD

**Issue by david-bouyssie** [jokade/slogging#41]
Even if SN 0.4.0-M2 is a milestone, it is quite stable and now used as a target for several projects.
It would thus be great to consider to release a version of slogging compatible with this Scala Native version.

Thanks.

**Comment by david-bouyssie** [comment]
Any plan for a new release?

To my knowledge, slogging is the only logging library for SN released so far, so it would be a nice step forward.
com.outr.scribe from @darkfrog26 has also a support for SN but it has not been released yet for this platform.

**Comment by darkfrog26** [comment]
@david-bouyssie look again my friend: https://search.maven.org/artifact/com.outr/scribe_native0.4.0-M2_2.11/2.7.11/jar

**Comment by darkfrog26** [comment]
Also worth noting that slogging hasn't updated its repo since March of 2018, so I wouldn't expect a lot going forward.  If there's something that Scribe is missing that slogging has, feel free to submit an issue for it.

**Comment by darkfrog26** [comment]
Also worth noting that slogging hasn't updated its repo since March of 2018, so I wouldn't expect a lot going forward.  If there's something that Scribe is missing that slogging has, feel free to submit an issue for it.

**Comment by darkfrog26** [comment]
Also worth noting that slogging hasn't updated its repo since March of 2018, so I wouldn't expect a lot going forward.  If there's something that Scribe is missing that slogging has, feel free to submit an issue for it.

**Comment by david-bouyssie** [comment]
@darkfrog26 thank you very much for this update. I'm going to try scribe with SN right now.

In the meantime @lolgab made a PR (https://github.com/jokade/slogging/pull/42) which is now pending.

**Comment by david-bouyssie** [comment]
@darkfrog26 I gave it a try and the scribe SN implementation seems to work for me. So thank you very much!

@jokade the merge of the PR from @lolgab is now less urgent since it isn't a blocker anymore but would be great if possible.

**Comment by jokade** [comment]
Sorry for the very long delay ... I've just released 0.6.2

**Comment by darkfrog26** [comment]
@jokade congrats man!
